language: c

dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code

notifications:
     webhooks:
       on_success: change  # options: [always|never|change] default: always
       on_failure: always  # options: [always|never|change] default: always
       on_start: false     # default: false
